// constants/universe.ts
// Repository-local, de-duplicated symbol universes. Index membership must be manually verified before relying on it as official current membership.

export const NASDAQ300 = [
  "AAPL","MSFT","NVDA","AMZN","META","GOOGL","GOOG","TSLA","AVGO","ADBE","COST","PEP","CSCO","NFLX","TMUS","INTC","AMD","QCOM","AMGN","TXN","HON","INTU","SBUX","BKNG","AMAT","ISRG","ADI","GILD","MU","LRCX","VRTX","MDLZ","REGN","PANW","SNPS","KLAC","MELI","CDNS","ASML","PDD","CRWD","ABNB","ADP","MAR","CTAS","CHTR","ORLY","PAYX","CSX","MRNA","KDP","NXPI","FTNT","WDAY","KHC","AEP","MNST","ROST","PCAR","EXC","AZN","ZS","TEAM","DDOG","MRVL","DXCM","BIIB","ILMN","IDXX","LULU","EA","ODFL","FAST","VRSK","XEL","GEHC","ANSS","CPRT","TTWO","MCHP","CTSH","FANG","WBD","BKR","DLTR","EBAY","SIRI","LCID","RIVN","ENPH","ALGN","WBA","DOCU","OKTA","NET","ROKU","COIN","SQ","PYPL","SHOP","ZM","U","PLTR","CRSP","NTES","BIDU","JD","BABA","NTDOY","TSM","SPLK","MDB","NOW","ARM","SMCI","ANET","GFS","ON","SGEN","ADSK","VOD","ERIC","TTD","MSTR","AFRM","FIVN","TWLO","PINS","SNOW","UBER","LYFT","DASH","EXPE","TRIP","ZG","Z","MTCH","RGEN","INCY","FOXA","FOX","ATVI","ULTA","KMB","HSIC","XRAY","WDC","STX","HPQ","DELL","LOGI","SWKS","QRVO","TER","GLW","NTAP","CDW","AKAM","CHKP","GEN","CYBR","DOCN","FSLY","ESTC","DT","GTLB","ASAN","HUBS","JBLU","SAVE","ALK","UAL","AAL","DAL","LUV","ZION","FITB","HBAN","RF","KEY","CFG","PNFP","SIVB","WAL","PACW","FULT","IBKR","SCHW","LPLA","HOOD","NDAQ","CME","ICE","MSCI","SPGI","FISV","PAYC","WEX","FIS","GPN","TOST","BILL","RIOT","MARA","HUT","CLSK","IREN","BTBT","NIO","XPEV","LI","F","GM","LAZR","MVIS","PTON","NWL","HAS","MAT","CROX","DECK","NKE","UAA","UA","SKX","ETSY","CHWY","W","OSTK","WMT","TGT","BJ","KR","SFM","WOOF","CVNA","KMX","ABG","PAG","GPI","LAD","KAR","PODD","TNDM","ALNY","BMRN","SRPT","IONS","EXAS","VCYT","FATE","BEAM","BNTX","NVAX","VIR","CRM","ORCL","SAP","IBM","HPE","STNE","NU","SE","GRAB","BOX","DBX","ZI","FROG","PATH","S","PTC","BSY","SSNC","MANH","MPWR","ENTG","VEEV","RPD","TENB","SNYK","SPOT"
];

export const NASDAQ100 = [
  "AAPL","MSFT","NVDA","AMZN","META","GOOGL","GOOG","TSLA","AVGO","ADBE","COST","PEP","CSCO","NFLX","TMUS","INTC","AMD","QCOM","AMGN","TXN","HON","INTU","SBUX","BKNG","AMAT","ISRG","ADI","GILD","MU","LRCX","VRTX","MDLZ","REGN","PANW","SNPS","KLAC","MELI","CDNS","ASML","PDD","CRWD","ABNB","ADP","MAR","CTAS","CHTR","ORLY","PAYX","CSX","MRNA","KDP","NXPI","FTNT","WDAY","KHC","AEP","MNST","ROST","PCAR","EXC","AZN","ZS","TEAM","DDOG","MRVL","DXCM","BIIB","ILMN","IDXX","LULU","EA","ODFL","FAST","VRSK","XEL","GEHC","ANSS","CPRT","TTWO","MCHP","CTSH","FANG","WBD","BKR","DLTR","EBAY","SIRI","LCID","RIVN","ENPH","ALGN","WBA","DOCU","OKTA","NET","ROKU","COIN","SQ","PYPL","SHOP"
];

export const ETFS = [
  "SPY","QQQ","IWM","DIA","VTI","VOO","SCHD","SMH","XLK","XLF",
  "XLE","XLV","XLY","XLP","XLI","XLB","XLU","XLC","GLD","TLT"
];

export const BIST100 = [
  "AKBNK","ALARK","ARCLK","ASELS","BIMAS","BRYAT","CIMSA","DOAS","EKGYO","ENJSA","EREGL","FROTO","GARAN","GUBRF","HALKB","HEKTS","ISCTR","KCHOL","KOZAA","KOZAL","KRDMD","MGROS","PETKM","SAHOL","SISE","TCELL","THYAO","TOASO","TTKOM","TUPRS","YKBNK","AKSA","ASUZU","BAGFS","BANVT","BERA","BRSAN","CCOLA","CANTE","CEMAS","CEMTS","CLEBI","CRFSA","CWENE","DURDO","EGEEN","ENKAI","FENER","GESAN","GIPTA","GOLTS","GWIND","HDFGS","INDES","ISMEN","KARSN","KERVT","KONYA","KORDS","KRVGD","LOGO","MAVI","MIATK","MPARK","NETAS","ODAS","OTKAR","OYAKC","PAPIL","PGSUS","POLTK","QUAGR","RAYSG","RTALB","SDTTR","SELEC","SMRTG","SNICA","SODSN","SUMAS","TAVHL","TKFEN","TRGYO","TSKB","TTRAK","TURGG","ULKER","USAK","VAKKO","VESBE","VESTL","YATAS","ZOREN","AGHOL","AGESA","AKGRT","ALCAR","LINK","AEFES","AKSEN"
];

export const EXPECTED_UNIVERSE_COUNTS = {
  NASDAQ100: 100,
  NASDAQ300: 281,
  BIST100: 100,
  ETFS: 20,
} as const;
