import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { clampAiScore } from "../lib/ai-utils.ts";
const auth = readFileSync("lib/server-auth.ts", "utf8");
assert.match(auth, /process\.env\.SCAN_SECRET/);
assert.match(auth, /bearer\(req\) \|\|[\s\S]*req\.headers\.get\("x-webhook-secret"\)[\s\S]*new URL\(req\.url\)\.searchParams\.get\("secret"\)[\s\S]*typeof body\?\.secret === "string"/);
assert.match(auth, /!expectedSecret \|\| !providedSecret \|\| providedSecret !== expectedSecret/);
assert.match(auth, /NextResponse\.json\(\{ ok: false, error: "Unauthorized" \}, \{ status: 401 \}\)/);
assert.match(auth, /Admin API is not configured/);
assert.match(auth, /authHeader !== `Bearer \$\{cronSecret\}`/);
assert.equal(clampAiScore(99), 10);
assert.equal(clampAiScore(-99), -10);
console.log("security validation ok");
