-- Create and document the TradingView/webhook signals table used by /api/signals.
-- Supabase CLI migration: run with `supabase db push` or link/apply via the Supabase dashboard.

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  symbol text not null,
  name text,
  signal text not null,
  price numeric,
  score numeric,
  reasons text,
  rvol numeric,
  timeframe text,
  type text not null default 'unknown',
  category text,
  exchange text,
  source text,
  outcome text,
  created_at timestamptz not null default now(),

  constraint signals_type_check check (type in ('stock', 'etf', 'unknown'))
);

-- Keep the migration safe for environments where an early `signals` table already exists.
alter table public.signals
  add column if not exists id bigint generated by default as identity,
  add column if not exists symbol text,
  add column if not exists name text,
  add column if not exists signal text,
  add column if not exists price numeric,
  add column if not exists score numeric,
  add column if not exists reasons text,
  add column if not exists rvol numeric,
  add column if not exists timeframe text,
  add column if not exists type text default 'unknown',
  add column if not exists category text,
  add column if not exists exchange text,
  add column if not exists source text,
  add column if not exists outcome text,
  add column if not exists created_at timestamptz default now();

alter table public.signals
  alter column type set default 'unknown',
  alter column created_at set default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.signals'::regclass
      and contype = 'p'
  ) then
    alter table public.signals
      add constraint signals_pkey primary key (id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'signals_type_check'
      and conrelid = 'public.signals'::regclass
  ) then
    alter table public.signals
      add constraint signals_type_check check (type in ('stock', 'etf', 'unknown'));
  end if;
end $$;

comment on table public.signals is
  'Signals received from TradingView/webhook ingestion and displayed by the dashboard.';

comment on column public.signals.id is 'Generated primary key for each signal.';
comment on column public.signals.symbol is 'Ticker or webhook symbol for the signal.';
comment on column public.signals.name is 'Display name for the instrument, when known.';
comment on column public.signals.signal is 'Signal direction/value, for example BUY or SELL.';
comment on column public.signals.price is 'Numeric-compatible signal price.';
comment on column public.signals.score is 'Numeric-compatible confidence or ranking score.';
comment on column public.signals.reasons is 'Nullable text explaining why the signal was generated.';
comment on column public.signals.rvol is 'Numeric-compatible relative volume value.';
comment on column public.signals.timeframe is 'Nullable source timeframe label.';
comment on column public.signals.type is 'Instrument type: stock, etf, or unknown for untracked webhook symbols.';
comment on column public.signals.category is 'Instrument category label.';
comment on column public.signals.exchange is 'Exchange or venue label.';
comment on column public.signals.source is 'Nullable source/provider label for the signal.';
comment on column public.signals.outcome is 'Optional manual result marker used by the dashboard, for example WIN or LOSS.';
comment on column public.signals.created_at is 'Signal creation timestamp, defaulting to now().';

create index if not exists signals_created_at_idx on public.signals (created_at desc);
create index if not exists signals_signal_score_created_at_idx on public.signals (signal, score desc, created_at desc);
