-- Document and provision the expected public.signals schema used by the app.
-- This migration is intentionally non-destructive for existing production data:
--   * CREATE TABLE IF NOT EXISTS preserves an existing table.
--   * ALTER TABLE ... ADD COLUMN IF NOT EXISTS only adds missing columns.
--   * Indexes are non-unique because duplicate handling is currently application-level
--     with a short time window, and existing production data/business rules are not
--     explicit enough to enforce a DB-level uniqueness constraint safely.

create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  symbol text not null,
  signal text not null,
  price numeric,
  score numeric,
  reasons text,
  timeframe text,
  outcome text
);

alter table public.signals
  add column if not exists id bigint generated by default as identity,
  add column if not exists created_at timestamptz default now(),
  add column if not exists symbol text,
  add column if not exists signal text,
  add column if not exists price numeric,
  add column if not exists score numeric,
  add column if not exists reasons text,
  add column if not exists timeframe text,
  add column if not exists outcome text;

comment on table public.signals is 'Trading signals consumed by /api/signals and signal dashboards.';
comment on column public.signals.id is 'Signal row identifier.';
comment on column public.signals.created_at is 'Signal creation timestamp; used for recency queries and duplicate checks.';
comment on column public.signals.symbol is 'Provider-normalized market symbol, for example NASDAQ:AAPL.';
comment on column public.signals.signal is 'Signal direction expected by the app, typically BUY or SELL.';
comment on column public.signals.price is 'Observed signal price when available.';
comment on column public.signals.score is 'Optional ranking score used by todayTop queries.';
comment on column public.signals.reasons is 'Optional human-readable reason text.';
comment on column public.signals.timeframe is 'Optional chart or strategy timeframe.';
comment on column public.signals.outcome is 'Optional manual result marker, expected values WIN, LOSS, or null.';

create index if not exists signals_created_at_idx
  on public.signals (created_at desc);

create index if not exists signals_symbol_signal_created_at_idx
  on public.signals (symbol, signal, created_at desc);

create index if not exists signals_signal_score_created_at_idx
  on public.signals (signal, score desc, created_at desc)
  where score is not null;
